### ISSUE TITLE
大部分都还是以太坊的，不能使用

### ISSUE THREAD

**Issue by MonveChen** [starcoinorg/stc-util#1]
有哪些是目前可以用的呢

**Comment by MonveChen** [comment]
> 有哪些是目前可以用的呢

正在接入贵方的sdk，能给个联系方式么

**Comment by tarvos21** [comment]
> > 有哪些是目前可以用的呢
> 
> 正在接入贵方的sdk，能给个联系方式么

感谢关注，这是个发版测试用的，目前还不能正常使用，一到两周内会有一个正式的版本发布出来。

starcoin.js SDK 使用上有什么问题，可以加我微信（peacedubing）
